/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SNMPv2-PDU"
 * 	found in "../RFC3416.asn1"
 */

#ifndef	_BulkPDU_H_
#define	_BulkPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "VarBindList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BulkPDU */
typedef struct BulkPDU {
	long	 request_id;
	long	 non_repeaters;
	long	 max_repetitions;
	VarBindList_t	 variable_bindings;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BulkPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BulkPDU;
extern asn_SEQUENCE_specifics_t asn_SPC_BulkPDU_specs_1;
extern asn_TYPE_member_t asn_MBR_BulkPDU_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _BulkPDU_H_ */
#include <asn_internal.h>
