/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SNMPv2-PDU"
 * 	found in "../RFC3416.asn1"
 */

#include "Gauge32.h"

int
Gauge32_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using Unsigned32,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_Gauge32_constr_1 CC_NOTUSED = {
	{ 4, 1 }	/* (0..4294967295) */,
	-1};
static asn_per_constraints_t asn_PER_type_Gauge32_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_Gauge32_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
asn_TYPE_descriptor_t asn_DEF_Gauge32 = {
	"Gauge32",
	"Gauge32",
	&asn_OP_NativeInteger,
	asn_DEF_Gauge32_tags_1,
	sizeof(asn_DEF_Gauge32_tags_1)
		/sizeof(asn_DEF_Gauge32_tags_1[0]) - 1, /* 1 */
	asn_DEF_Gauge32_tags_1,	/* Same as above */
	sizeof(asn_DEF_Gauge32_tags_1)
		/sizeof(asn_DEF_Gauge32_tags_1[0]), /* 2 */
	{ &asn_OER_type_Gauge32_constr_1, &asn_PER_type_Gauge32_constr_1, Gauge32_constraint },
	0, 0,	/* No members */
	&asn_SPC_Unsigned32_specs_1	/* Additional specs */
};

