/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SNMPv2-PDU"
 * 	found in "../RFC3416.asn1"
 */

#ifndef	_SimpleSyntax_H_
#define	_SimpleSyntax_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <OBJECT_IDENTIFIER.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SimpleSyntax_PR {
	SimpleSyntax_PR_NOTHING,	/* No components present */
	SimpleSyntax_PR_integer_value,
	SimpleSyntax_PR_string_value,
	SimpleSyntax_PR_objectID_value
} SimpleSyntax_PR;

/* SimpleSyntax */
typedef struct SimpleSyntax {
	SimpleSyntax_PR present;
	union SimpleSyntax_u {
		long	 integer_value;
		OCTET_STRING_t	 string_value;
		OBJECT_IDENTIFIER_t	 objectID_value;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SimpleSyntax_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SimpleSyntax;
extern asn_CHOICE_specifics_t asn_SPC_SimpleSyntax_specs_1;
extern asn_TYPE_member_t asn_MBR_SimpleSyntax_1[3];
extern asn_per_constraints_t asn_PER_type_SimpleSyntax_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SimpleSyntax_H_ */
#include <asn_internal.h>
