/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_Gauge32;
extern struct asn_TYPE_descriptor_s asn_DEF_PDUs;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module COMMUNITY-BASED-SNMPv2 in ../RFC1901.asn1 */
	&asn_DEF_Message,	
	/* From module SNMPv2-PDU in ../RFC3416.asn1 */
	&asn_DEF_Gauge32,	
	&asn_DEF_PDUs,	
	0
};

