/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SNMPv2-PDU"
 * 	found in "../RFC3416.asn1"
 */

#include "PDUs.h"

static asn_oer_constraints_t asn_OER_type_PDUs_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_PDUs_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_PDUs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.get_request),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_GetRequest_PDU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"get-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.get_next_request),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_GetNextRequest_PDU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"get-next-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.get_bulk_request),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_GetBulkRequest_PDU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"get-bulk-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.response),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_Response_PDU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"response"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.set_request),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_SetRequest_PDU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"set-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.inform_request),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		0,
		&asn_DEF_InformRequest_PDU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"inform-request"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.snmpV2_trap),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		0,
		&asn_DEF_SNMPv2_Trap_PDU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"snmpV2-trap"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUs, choice.report),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		0,
		&asn_DEF_Report_PDU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"report"
		},
};
static const unsigned asn_MAP_PDUs_to_canonical_1[] = { 0, 1, 3, 4, 2, 5, 6, 7 };
static const unsigned asn_MAP_PDUs_from_canonical_1[] = { 0, 1, 4, 2, 3, 5, 6, 7 };
static const asn_TYPE_tag2member_t asn_MAP_PDUs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* get-request */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* get-next-request */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, 0, 0 }, /* response */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 4, 0, 0 }, /* set-request */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, 0, 0 }, /* get-bulk-request */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* inform-request */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* snmpV2-trap */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 7, 0, 0 } /* report */
};
static asn_CHOICE_specifics_t asn_SPC_PDUs_specs_1 = {
	sizeof(struct PDUs),
	offsetof(struct PDUs, _asn_ctx),
	offsetof(struct PDUs, present),
	sizeof(((struct PDUs *)0)->present),
	asn_MAP_PDUs_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_PDUs_to_canonical_1,
	asn_MAP_PDUs_from_canonical_1,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_PDUs = {
	"PDUs",
	"PDUs",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_PDUs_constr_1, &asn_PER_type_PDUs_constr_1, CHOICE_constraint },
	asn_MBR_PDUs_1,
	8,	/* Elements count */
	&asn_SPC_PDUs_specs_1	/* Additional specs */
};

