/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SNMPv2-PDU"
 * 	found in "../RFC3416/RFC3416.asn1"
 */

#include "BulkPDU.h"

static int
memb_request_id_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -214783648 && value <= 214783647)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_non_repeaters_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 2147483647)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_max_repetitions_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 2147483647)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_request_id_constr_2 CC_NOTUSED = {
	{ 4, 0 }	/* (-214783648..214783647) */,
	-1};
static asn_per_constraints_t asn_PER_memb_request_id_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 29, -1, -214783648,  214783647 }	/* (-214783648..214783647) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_non_repeaters_constr_3 CC_NOTUSED = {
	{ 4, 1 }	/* (0..2147483647) */,
	-1};
static asn_per_constraints_t asn_PER_memb_non_repeaters_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 31, -1,  0,  2147483647 }	/* (0..2147483647) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_max_repetitions_constr_4 CC_NOTUSED = {
	{ 4, 1 }	/* (0..2147483647) */,
	-1};
static asn_per_constraints_t asn_PER_memb_max_repetitions_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 31, -1,  0,  2147483647 }	/* (0..2147483647) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_BulkPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BulkPDU, request_id),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_request_id_constr_2, &asn_PER_memb_request_id_constr_2,  memb_request_id_constraint_1 },
		0, 0, /* No default value */
		"request-id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BulkPDU, non_repeaters),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_non_repeaters_constr_3, &asn_PER_memb_non_repeaters_constr_3,  memb_non_repeaters_constraint_1 },
		0, 0, /* No default value */
		"non-repeaters"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BulkPDU, max_repetitions),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_max_repetitions_constr_4, &asn_PER_memb_max_repetitions_constr_4,  memb_max_repetitions_constraint_1 },
		0, 0, /* No default value */
		"max-repetitions"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BulkPDU, variable_bindings),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_VarBindList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"variable-bindings"
		},
};
static const ber_tlv_tag_t asn_DEF_BulkPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BulkPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 2 }, /* request-id */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 1 }, /* non-repeaters */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 0 }, /* max-repetitions */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, 0, 0 } /* variable-bindings */
};
asn_SEQUENCE_specifics_t asn_SPC_BulkPDU_specs_1 = {
	sizeof(struct BulkPDU),
	offsetof(struct BulkPDU, _asn_ctx),
	asn_MAP_BulkPDU_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_BulkPDU = {
	"BulkPDU",
	"BulkPDU",
	&asn_OP_SEQUENCE,
	asn_DEF_BulkPDU_tags_1,
	sizeof(asn_DEF_BulkPDU_tags_1)
		/sizeof(asn_DEF_BulkPDU_tags_1[0]), /* 1 */
	asn_DEF_BulkPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_BulkPDU_tags_1)
		/sizeof(asn_DEF_BulkPDU_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_BulkPDU_1,
	4,	/* Elements count */
	&asn_SPC_BulkPDU_specs_1	/* Additional specs */
};

