/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SNMPv2-PDU"
 * 	found in "../RFC3416/RFC3416.asn1"
 */

#include "ObjectSyntax.h"

static asn_oer_constraints_t asn_OER_type_ObjectSyntax_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ObjectSyntax_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ObjectSyntax_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectSyntax, choice.simple),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_SimpleSyntax,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"simple"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ObjectSyntax, choice.application_wide),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ApplicationSyntax,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"application-wide"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ObjectSyntax_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* integer-value */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 }, /* string-value */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* objectID-value */
    { (ASN_TAG_CLASS_APPLICATION | (0 << 2)), 1, 0, 0 }, /* ipAddress-value */
    { (ASN_TAG_CLASS_APPLICATION | (1 << 2)), 1, 0, 0 }, /* counter-value */
    { (ASN_TAG_CLASS_APPLICATION | (2 << 2)), 1, 0, 0 }, /* unsigned-integer-value */
    { (ASN_TAG_CLASS_APPLICATION | (3 << 2)), 1, 0, 0 }, /* timeticks-value */
    { (ASN_TAG_CLASS_APPLICATION | (4 << 2)), 1, 0, 0 }, /* arbitrary-value */
    { (ASN_TAG_CLASS_APPLICATION | (6 << 2)), 1, 0, 0 } /* big-counter-value */
};
asn_CHOICE_specifics_t asn_SPC_ObjectSyntax_specs_1 = {
	sizeof(struct ObjectSyntax),
	offsetof(struct ObjectSyntax, _asn_ctx),
	offsetof(struct ObjectSyntax, present),
	sizeof(((struct ObjectSyntax *)0)->present),
	asn_MAP_ObjectSyntax_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ObjectSyntax = {
	"ObjectSyntax",
	"ObjectSyntax",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ObjectSyntax_constr_1, &asn_PER_type_ObjectSyntax_constr_1, CHOICE_constraint },
	asn_MBR_ObjectSyntax_1,
	2,	/* Elements count */
	&asn_SPC_ObjectSyntax_specs_1	/* Additional specs */
};

